name       : signond
version    : 8.6
release    : 5
source     :
    - git|https://gitlab.com/accounts-sso/signond.git : VERSION_8.60
license    : LGPL-2.1-only
component  : programming
summary    : Qt SignOn Daemon
description: |
    Framework to provide credential storage and authentication service for SSO
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5WebKit)
    - doxygen
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-static-libs.patch
    %patch -p1 < $pkgfiles/0002-Dont-use-fno-rtti.patch
    %patch -p1 < $pkgfiles/0003-Port-away-from-QHash.patch
    %qmake PREFIX=%PREFIX% LIBDIR=%libdir%
build      : |
    %make
install    : |-
    %make_install INSTALL_ROOT="$installdir"
    # Remove HTML docs
    rm -rf $installdir/usr/share/doc/
