name       : signond
version    : 8.59
release    : 2
source     :
    - git|https://gitlab.com/accounts-sso/signond.git : 4e5b6a9a20636c40b2c8c186f938763ad943c49c
license    : LGPL-2.1-only
component  : programming
summary    : Qt SignOn Daemon
description: |
    Framework to provide credential storage and authentication service for SSO
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5WebKit)
    - doxygen
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-static-libs.patch
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
